### ISSUE TITLE
On build on change to Dockerfile causes all builds to fail

### ISSUE THREAD

**Issue by n3ddu8** [n3ddu8/ubuntu-odbc#1]
Expected change to workflow file would only initiate build when `Dockerfile` is updated, however this causes all builds to fail. Have reverted change for now but would like to revisit. Change looks like:
```yml
 on:
   push:
     branches: ['main']
   paths:
     - 'Dockerfile'
```
